version: '3.8'

services:
  web:
    build: ./fastapi_app
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin_user:admin_password@main_db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  bot:
    build: ./telegram_bot
    container_name: telegram_bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=token:token
    depends_on:
      - redis

  worker:
    build: ./redis_app
    container_name: redis_app
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: main_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always

volumes:
  pgdata:
