version: '3.11'

services:
  fastapi_app:
    build: .
    command: python -m uvicorn main:app
    volumes:
      - ./:/usr/src/fastapi_app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
  telegram_bot:
    build: .
    command: python bot.py
    volumes:
        - ./:/usr/src/telegram_bot/
    ports:
        - 8001:8001
    env_file:
        - ./.env
  redis_worker:
    build: .
    command: python redis_worker.py
    volumes:
      - ./:/usr/src/redis_app/
    ports:
      - 8002:8002
    env_file:
      - ./.env
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - ./.env